import {
  IconHome2,
  IconUser,
  IconSettings,
  IconSearch,
  IconDots,
  IconLayoutSidebarRightCollapse,
  IconCheck,
  IconX,
  IconAlertTriangle,
  IconBrandGoogle,
  IconArrowLeft,
  IconMinusVertical,
  IconSlash,
  IconShieldLock,
  IconAlertCircle,
  IconHourglassHigh,
  IconLock,
  IconMail,
} from "@tabler/icons-react";

export {
  IconHome2 as Home,
  IconUser as User,
  IconSettings as Settings,
  IconSearch as Search,
  IconDots as Dots,
  IconLayoutSidebarRightCollapse as Collapse,
  IconCheck as Check,
  IconX as X,
  IconAlertTriangle as AlertTriangle,
  IconBrandGoogle as Google,
  IconArrowLeft as ArrowLeft,
  IconMinusVertical as MinusVertical,
  IconSlash as Slash,
  IconShieldLock as ShieldLock,
  IconAlertCircle as AlertCircle,
  IconHourglassHigh as HourglassHigh,
  IconLock as Lock,
  IconMail as Mail,
};
